apiVersion: k8s.linki.space/v1alpha1
kind: EncryptedSecret
metadata:
  name: encrypted-secret-example
spec:
  # the provider where the secret is stored
  #
  # either 'GCP' for Google's Cloud Key Management Service
  #   https://cloud.google.com/kms/
  # or 'AWS' for AWS Key Management Service (KMS)
  #   https://aws.amazon.com/kms/
  provider: GCP

  # reference to the key to use for decryption within the provider
  # this is only needed when provider is GCP
  keyID: projects/.../locations/.../keyRings/.../cryptoKeys/...

  # the base64 encoded ciphertext
  ciphertext: ...
