apiVersion: k8s.linki.space/v1alpha1
kind: ManagedSecret
metadata:
  name: managed-secret-example
spec:
  # the provider where the secret is stored
  #
  # either 'GCP' for Google Cloud Platform's Secret Manager
  #   https://cloud.google.com/secret-manager/
  # or 'AWS' for AWS Secrets Manager
  #   https://aws.amazon.com/secrets-manager/
  provider: GCP

  data:
    # reference to the secret within the provider
    #
    # for GCP: use full reference to the secret's version
    # for AWS: use the secret's ARN or its friendly name
    my_password: projects/.../secrets/.../versions/1
