# permissions for end users to view encryptedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: encryptedsecret-viewer-role
rules:
- apiGroups:
  - k8s.linki.space
  resources:
  - encryptedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.linki.space
  resources:
  - encryptedsecrets/status
  verbs:
  - get
