# permissions for end users to edit managedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedsecret-editor-role
rules:
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets/status
  verbs:
  - get
