# permissions for end users to view managedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedsecret-viewer-role
rules:
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets/status
  verbs:
  - get
