
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s.linki.dev
  resources:
  - encryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.linki.dev
  resources:
  - encryptedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.linki.dev
  resources:
  - encryptedsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.linki.dev
  resources:
  - managedsecrets/status
  verbs:
  - get
  - patch
  - update
