apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedsecrets.k8s.linki.space
spec:
  group: k8s.linki.space
  names:
    kind: ManagedSecret
    listKind: ManagedSecretList
    plural: managedsecrets
    singular: managedsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ManagedSecret is the Schema for the managedsecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ManagedSecretSpec defines the desired state of ManagedSecret
          properties:
            data:
              additionalProperties:
                type: string
              type: object
            provider:
              enum:
              - AWS
              - GCP
              - Identity
              type: string
          required:
          - data
          - provider
          type: object
        status:
          description: ManagedSecretStatus defines the observed state of ManagedSecret
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
