apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypted-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      name: encrypted-secrets
  template:
    metadata:
      labels:
        name: encrypted-secrets
    spec:
      serviceAccountName: encrypted-secrets
      containers:
        - name: encrypted-secrets
          image: quay.io/linki/encrypted-secrets
          command:
          - encrypted-secrets
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "encrypted-secrets"
