kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: encrypted-secrets
subjects:
- kind: ServiceAccount
  name: encrypted-secrets
roleRef:
  kind: Role
  name: encrypted-secrets
  apiGroup: rbac.authorization.k8s.io
