apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypted-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: encrypted-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: encrypted-secrets
      annotations:
        iam.amazonaws.com/role: encrypted-secrets
    spec:
      serviceAccountName: encrypted-secrets
      containers:
      - name: encrypted-secrets
        image: quay.io/linki/encrypted-secrets
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: encrypted-secrets
